# Generated by Django 3.2.7 on 2021-11-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='valor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
