# Generated by Django 3.2.9 on 2021-11-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0002_procedimento_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
