# Generated by Django 3.2.7 on 2021-10-29 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locaisAtendimentos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('procedimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('hora', models.TimeField()),
                ('cor', models.CharField(max_length=10)),
                ('obs_agenda', models.TextField()),
                ('sessoes', models.IntegerField()),
                ('cancelado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('local_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locaisAtendimentos.locaisatendimento')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimentos.procedimento')),
            ],
        ),
    ]
