# Generated by Django 3.2.9 on 2021-11-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locaisAtendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locaisatendimento',
            name='endereco',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='locaisatendimento',
            name='local',
            field=models.TextField(max_length=100),
        ),
    ]
