# Generated by Django 3.2.7 on 2021-11-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('procedimentos', '0002_procedimento_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('cliente', models.TextField()),
                ('data_venda', models.DateField()),
                ('hora_venda', models.DateTimeField()),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.agendamento')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimentos.procedimento')),
            ],
        ),
    ]
