# Generated by Django 3.2.7 on 2021-11-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='hora_venda',
            field=models.TimeField(),
        ),
    ]
