# Generated by Django 3.2.7 on 2021-11-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_vendas_hora_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_venda',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='hora_venda',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
