# Generated by Django 3.2.7 on 2021-11-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_telefone'),
        ('financeiro', '0003_auto_20211111_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='data_vencimento',
            field=models.DateField(default='2021-11-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendas',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendas',
            name='tipo_compra',
            field=models.CharField(choices=[('av', 'À vista'), ('pc', 'Parcelado'), ('mt', 'Misto')], default='av', max_length=2),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
        ),
    ]
