# Generated by Django 3.2.7 on 2021-11-12 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('financeiro', '0004_auto_20211112_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='agendamento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agendamentos.agendamento'),
        ),
    ]
