# Generated by Django 3.2.9 on 2021-11-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_alter_vendas_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='valor_cartao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendas',
            name='valor_dinheiro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
