# Generated by Django 3.2.9 on 2021-11-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_auto_20211126_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('procedimentos', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='vendas',
            name='encerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendas',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
