# Generated by Django 3.2.7 on 2021-10-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
