# Generated by Django 3.2.7 on 2021-11-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.FloatField(max_length=4)),
                ('peso', models.FloatField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='peso',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cep',
            field=models.TextField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='cpf',
            field=models.TextField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado_civil',
            field=models.TextField(choices=[('st', 'Solteira(o'), ('cs', 'Casada(o)'), ('dv', 'Divorciada(o)')], default='st', max_length=2),
        ),
        migrations.AddField(
            model_name='clientes',
            name='rg',
            field=models.TextField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='sexo',
            field=models.TextField(choices=[('fm', 'Feminino'), ('ms', 'Masculino')], default='fm', max_length=2),
        ),
    ]
