# Generated by Django 3.2.7 on 2021-11-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20211116_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado_civil',
            field=models.TextField(choices=[('st', 'Solteira(o'), ('cs', 'Casada(o)'), ('dv', 'Divorciada(o)'), ('vv', 'Viúva(o)')], default='st', max_length=2),
        ),
    ]
