# Generated by Django 3.2.7 on 2021-11-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_clientes_estado_civil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='estado_civil',
            new_name='estadocivil',
        ),
    ]
