# Generated by Django 3.2.7 on 2021-11-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_rename_estado_civil_clientes_estadocivil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='estadocivil',
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado_civil',
            field=models.TextField(choices=[('st', 'Solteira(o)'), ('cs', 'Casada(o)'), ('dv', 'Divorciada(o)'), ('vv', 'Viúva(o)')], default='st', max_length=2),
        ),
    ]
