# Generated by Django 3.2.7 on 2021-11-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20211116_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado_civil',
            field=models.TextField(choices=[('Feminino', (('st', 'Solteira'), ('cs', 'Casada'))), ('Masculino', (('st', 'Solteiro'), ('cs', 'Casado')))], default='st', max_length=2),
        ),
    ]
