# Generated by Django 3.2.7 on 2021-11-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_clientes_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado_civil',
            field=models.TextField(choices=[('Feminino', (('st', 'Solteira'), ('cs', 'Casada'), ('vv', 'Viúva'), ('dv', 'Divorciada'))), ('Masculino', (('st', 'Solteiro'), ('cs', 'Casado'), ('vv', 'Viúvo'), ('dv', 'Divorciado')))], default='st', max_length=2),
        ),
    ]
