# Generated by Django 3.2.7 on 2021-11-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_clientes_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='alergia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='alergia_txt',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='atividade_fisica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='atividade_fisica_txt',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='bebe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='cirurgia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='cirurgia_txt',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='cliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anamnese',
            name='epilepsia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='filhos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='filhos_qt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='fumante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='gestante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='hipertensao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='ingestao_liquido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='ingestao_liquido_txt',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='intestino_regular',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='lesoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='lesoes_txt',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='menstruacao_regular',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='problema_oncologico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='problema_oncologico_txt',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='problema_ortopedico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='problema_ortopedico_txt',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tratamento_estetico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tratamento_estetico_txt',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tratamento_medico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tratamento_medico_txt',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tratamento_ortomolecular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tratamento_ortomolecular_txt',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_acido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_acido_txt',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_anticonsepcional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_anticonsepcional_txt',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_marcapasso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_metais',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_metais_txt',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_produtos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_produtos_txt',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='varizes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='varizes_txt',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado_civil',
            field=models.TextField(choices=[('Feminino', (('sta', 'Solteira'), ('csa', 'Casada'), ('vva', 'Viúva'), ('dva', 'Divorciada'))), ('Masculino', (('st', 'Solteiro'), ('cs', 'Casado'), ('vv', 'Viúvo'), ('dv', 'Divorciado')))], default='sta', max_length=3),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='obs',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
