# Generated by Django 3.2.9 on 2021-11-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20211117_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='obs',
            field=models.TextField(blank=True, default='Nenhuma', max_length=400),
        ),
    ]
