# Generated by Django 3.2.9 on 2021-11-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_clientes_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='atividade_fisica_txt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='cirurgia_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='ingestao_liquido_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='lesoes_txt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='problema_oncologico_txt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='problema_ortopedico_txt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='tratamento_estetico_txt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='tratamento_medico_txt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='tratamento_ortomolecular_txt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='usa_acido_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='usa_anticonsepcional_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='usa_metais_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='usa_produtos_txt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='varizes_txt',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
