# Generated by Django 3.2.9 on 2021-11-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20211130_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='alergia_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
